package com.udmconsulting.integrations.hubspot.oauth.application;

public enum HubSpotOAuthFailureCategory {
    TOKEN_EXCHANGE_REJECTED,
    TOKEN_EXCHANGE_PROVIDER_UNAVAILABLE,
    TOKEN_RESPONSE_INVALID,
    TOKEN_INTROSPECTION_REJECTED,
    TOKEN_INTROSPECTION_PROVIDER_UNAVAILABLE,
    TOKEN_METADATA_INVALID,
    ACCOUNT_IDENTITY_MISMATCH,
    REQUIRED_SCOPE_MISSING,
    LOCAL_FINALIZATION_FAILED
}
