package com.udmconsulting.platform.activity.domain;

public enum ActivityAction {
    PLATFORM_CONNECTION_ACTIVATED,
    PLATFORM_CONNECTION_REAUTHORIZED,
    PLATFORM_CONNECTION_REAUTHENTICATION_REQUIRED,
    PLATFORM_CONNECTION_DISCONNECTED,
    ENTITLEMENT_ACTIVATED,
    ENTITLEMENT_DEACTIVATED
}
