package com.udmconsulting.platform.activity.domain;

public enum ActivityAction {
    PLATFORM_CONNECTION_ACTIVATED,
    PLATFORM_CONNECTION_REAUTHORIZED,
    PLATFORM_CONNECTION_REAUTHENTICATION_REQUIRED,
    PLATFORM_CONNECTION_DISCONNECTED,
    ENTITLEMENT_ACTIVATED,
    ENTITLEMENT_DEACTIVATED,
    LINE_ITEM_SIGNAL_REQUEUED,
    LINE_ITEM_RECONCILIATION_REQUESTED,
    LINE_ITEM_REPLAY_REQUESTED,
    LINE_ITEM_RETENTION_EXECUTED,
    LINE_ITEM_FINDING_ACKNOWLEDGED,
    LINE_ITEM_GAP_ACKNOWLEDGED
}
