package com.udmconsulting.platform.supportability;

public enum OperationalErrorCode {
    NONE,
    INVALID_REQUEST,
    AUTHENTICATION_FAILED,
    ACCOUNT_UNAVAILABLE,
    REQUEST_BODY_READ_FAILED,
    WEBHOOK_PAYLOAD_INVALID,
    DATABASE_UNAVAILABLE,
    PROVIDER_AUTH_REQUIRED,
    PROVIDER_UNAVAILABLE,
    CONCURRENT_STATE_CHANGE,
    INVARIANT_VIOLATION,
    INTERNAL_ERROR,
    STALE_CLAIM,
    INVALID_SIGNAL_VALUE,
    TRANSIENT_DATABASE,
    INTERNAL_PROCESSING
}
